-- =============================================
-- БАЗА ДАННЫХ ПРОЕКТА "АЙБОЛИТ"
-- СУБД: PostgreSQL (Supabase)
-- =============================================

-- 1. Таблица ВРАЧЕЙ (Doctors)
-- Хранит информацию о специалистах, их график и биографию
CREATE TABLE IF NOT EXISTS public.doctors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,                -- ФИО врача
    specialization text,               -- Специализация (Хирург, Терапевт...)
    experience text,                   -- Стаж (напр. "12 лет")
    bio text,                          -- Краткая биография
    image_url text,                    -- Ссылка на фото
    work_start_hour integer DEFAULT 9, -- Начало смены (часы)
    work_end_hour integer DEFAULT 18   -- Конец смены (часы)
);

-- 2. Таблица ВЛАДЕЛЬЦЕВ (Owners)
-- Хранит контактные данные клиентов
CREATE TABLE IF NOT EXISTS public.owners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,           -- Имя владельца
    phone text NOT NULL UNIQUE         -- Телефон (уникальный идентификатор для входа)
);

-- 3. Таблица ПИТОМЦЕВ (Pets)
-- Связана с владельцем. Хранит медкарту животного.
CREATE TABLE IF NOT EXISTS public.pets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    owner_id bigint REFERENCES public.owners(id) ON DELETE CASCADE, -- Связь с владельцем
    name text NOT NULL,                -- Кличка
    type text NOT NULL,                -- Вид (Собака, Кошка...)
    breed text,                        -- Порода
    age text,                          -- Возраст
    weight text,                       -- Вес (добавлено для медкарты)
    past_injuries text,                -- Хронические болезни/травмы
    has_visited_before boolean DEFAULT false -- Был ли ранее в клинике
);

-- 4. Таблица ЗАПИСЕЙ НА ПРИЕМ (Appointments)
-- Связывает питомца и врача. Хранит историю болезни.
CREATE TABLE IF NOT EXISTS public.appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    pet_id bigint REFERENCES public.pets(id) ON DELETE CASCADE,    -- Кого лечим
    doctor_id bigint REFERENCES public.doctors(id) ON DELETE SET NULL, -- Кто лечит
    date_time timestamp without time zone NOT NULL, -- Дата и время приема
    comment text,                      -- Жалоба владельца
    status text DEFAULT 'new',         -- Статус (new, done, canceled)
    diagnosis text                     -- Врачебное заключение (добавлено для режима врача)
);

-- =============================================
-- ЗАПОЛНЕНИЕ ТЕСТОВЫМИ ДАННЫМИ (SEED DATA)
-- =============================================

-- Вставка врачей
INSERT INTO public.doctors (name, specialization, experience, bio, image_url, work_start_hour, work_end_hour)
VALUES 
(
    'Хаус Грегори', 
    'Инфекционист, Нефролог, Диагност', 
    'Стаж: 20 лет', 
    'Гениальный диагност с нестандартным подходом. Специализируется на сложнейших случаях, когда другие врачи разводят руками. Мизантроп, но результат гарантирует.',
    'https://upload.wikimedia.org/wikipedia/en/1/1c/Hugh_Laurie_as_Gregory_House.jpg',
    10, 18
),
(
    'Быков Андрей Евгеньевич', 
    'Терапевт, Заведующий отделением', 
    'Стаж: 15 лет', 
    'Опытный руководитель и блестящий клиницист. Картавый, циничный, но справедливый. Любит дисциплину и не терпит глупости.',
    'https://upload.wikimedia.org/wikipedia/ru/3/37/Bykov.jpg',
    8, 16
),
(
    'Айболит', 
    'Ветеринар-универсал', 
    'Стаж: Бесконечный', 
    'Легендарный специалист широкого профиля. Лечит всех: от жучков до китов. Готов отправиться в Лимпопо ради пациента.',
    'https://skazki.rustih.ru/wp-content/uploads/2018/06/doktor-ajbolit-kornej-chukovskij.jpg',
    0, 24
);

-- Пример клиента
INSERT INTO public.owners (full_name, phone)
VALUES ('Тестовый Иван Иванович', '+7 (999) 000-00-00');

-- Пример питомца для этого клиента
INSERT INTO public.pets (owner_id, name, type, breed, age, weight, past_injuries)
VALUES (
    (SELECT id FROM public.owners WHERE phone = '+7 (999) 000-00-00'), 
    'Шарик', 
    'dog', 
    'Двортерьер', 
    '3 года', 
    '12 кг', 
    'Аллергия на дешевый корм'
);